apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  namespace: skala-gj4
spec:
  ingressClassName: nginx
  rules:
    - host: skala-gj4-myapp.skala-gj.com
  http:
  paths:
  - path: /
  pathType: Prefix
  backend:
  service:
  name: myapp
  port:
  number: 80